### ISSUE TITLE
Remove the notifier component for Slack from Airnode's Github Actions

### ISSUE THREAD

**Issue by dcroote** [api3dao/airkeeper#87]
As in https://github.com/api3dao/airnode/issues/1414

**Comment by andreogle** [comment]
Thanks for opening this issue. I'll keep the Slack channel around until this is done. Airkeeper seems to be the only other project posting to Slack

**Comment by dcroote** [comment]
Sure thing @andreogle. I didn't see any other repos posting to the channel either so I think with this merged the channel can be archived.

**Comment by andreogle** [comment]
Channel archived 👍🏻
